### ISSUE TITLE
Previsão de publicação dos dados

### ISSUE THREAD

**Issue by rafapereirabr** [Gabriel-Assuncao/PNDSIBGE#1]
Oi Gabriel, existe alguma previsão de quando os dados da PNDS serão publicados e disponibilizados no pacote?

**Comment by Gabriel-Assuncao** [comment]
Prezado @rafapereirabr, boa tarde.
Ainda não existe uma data definida para a primeira divulgação da PNDS e portanto liberação da versão consolidada do pacote PNDSIBGE, pois atualmente a pesquisa está em fase de tratamento e preparação dos dados coletados. Assim que houver uma previsão, possivelmente a informação ficará disponível através do cronograma de divulgação da [Agência de Notícias do IBGE](https://agenciadenoticias.ibge.gov.br/pt/agencia-home.html).
Irei realizar o fechamento desta _issue_, mas permanecemos a disposição através do canal de atendimento pacotesipd@ibge.gov.br.
